### ISSUE TITLE
Error when btaddr config file does not exist

### ISSUE THREAD

**Issue by dlech** [mvidner/lignite#1]
Using lignite 0.1.0 installed from gem.

When running `ev3tool` with no USB attached, I get the following error:

```
/home/david/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/lignite-0.1.0/lib/lignite/connection/bluetooth.rb:24:in `read': No such file or directory @ rb_sysopen - /home/david/.config/lignite-btaddr (Errno::ENOENT)
        from /home/david/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/lignite-0.1.0/lib/lignite/connection/bluetooth.rb:24:in `address_from_file'
        from /home/david/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/lignite-0.1.0/lib/lignite/connection/bluetooth.rb:10:in `initialize'
        from /home/david/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/lignite-0.1.0/lib/lignite/connection.rb:8:in `new'
        from /home/david/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/lignite-0.1.0/lib/lignite/connection.rb:8:in `rescue in create'
        from /home/david/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/lignite-0.1.0/lib/lignite/connection.rb:5:in `create'
        from /home/david/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/lignite-0.1.0/lib/lignite/system_commands.rb:8:in `initialize'
        from /home/david/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/lignite-0.1.0/bin/ev3tool:58:in `new'
        from /home/david/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/lignite-0.1.0/bin/ev3tool:58:in `<top (required)>'
        from /home/david/.rbenv/versions/2.1.7/bin/ev3tool:23:in `load'
        from /home/david/.rbenv/versions/2.1.7/bin/ev3tool:23:in `<main>'
```

**Comment by dlech** [comment]
so, I guess it would be nice if `ev3tool` told you to attach via USB or create a BT config file instead of a stack trace.

**Comment by dlech** [comment]
or, even better, create the config file automatically

**Comment by mvidner** [comment]
Thanks so much for all the quick and detailed feedback, David!

**Comment by dlech** [comment]
You are welcome. I'm not very familiar with ruby, but this looks very nice to me. And with some more documentation and some higher level api, it will be even better.

A funny thing happened though... I tried to use code completion and my robot would sometimes drive when I pressed CTRL+SPACE since ruby is a dynamic language and some of it has to be executed for code completion to work.

**Comment by mvidner** [comment]
> I tried to use code completion and my robot would sometimes drive when I pressed CTRL+SPACE since ruby is a dynamic language and some of it has to be executed for code completion to work.

Oh, that should not happen. Was that in `irb`, `pry`, or some IDE? Consider filing a new issue for this.
