### ISSUE TITLE
Using code completion in VSCode with Ruby extension (rebornix.ruby) causes motors to run

### ISSUE THREAD

**Issue by dlech** [mvidner/lignite#5]
Steps to repeat:

1. install [Visual Studio Code](https://code.visualstudio.com/)
2. install [Ruby extension](https://marketplace.visualstudio.com/items?itemName=rebornix.Ruby) in VSCode 
3. install `lignite` 0.1.0 from gem
4. install `rcodetools` from gem for code completion
5. open the [motor demo](https://github.com/mvidner/lignite/blob/master/examples/motors.rb) in VSCode
6. Run the demo from a command line to make sure communication to robot is working
7. Place cursor on the end of the line `dc.output_ready(layer, nos)`
8. Press CTRL+SPACE for code completion
9. The motors run briefly!

**Comment by mvidner** [comment]
OK, I think it is a misfeature of [rcodetools](http://www.eigenclass.org/hiki/rcodetools/):

> ### Caveat emptor
> The rcodetools execute your programs; in particular, rct-complete will run your code when you attempt to perform code completion! Keep this in mind if your code has got side-effects such as files being deleted, emails sent, etc...

I'm afraid I cannot help with that.

**Comment by dlech** [comment]
That is what I thought. :smile:
